### ISSUE TITLE
Identifiquei um novo erro, parece que ao usarem demais o bot uma hora da um erro no comando rank, segue o erro abaixo:

### ISSUE THREAD

**Issue by thiagogebrim13** [TiaGoiNsaNy/BotEconomiaQuickDB#7]
```
(node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tag' of undefined
    at Object.module.exports.run (/home/container/commands/rank.js:18:68)
    at Client.<anonymous> (/home/container/index.js:45:18)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:314:20)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sprayx** [comment]
Como assim "se usarem demais o bot?"

**Comment by thiagogebrim13** [comment]
Me desculpe, dei uma analisada melhor e sempre que um usuario se torna "infedinido" acredito que o que cause isso é a saida dele do discord da esse erro caso ele esteja no top money.

**Comment by TiaGoiNsaNy** [comment]
Isso está relacionado aos **Discord Intents**, você precisa habilitar as duas opções no painel de controle de sua aplicação.

**Comment by thiagogebrim13** [comment]
Está ativo

**Comment by WinG4merBR** [comment]
Na hora de declarar o client coloca o seguinte:
```js
const client = new Client({
    ws: {
        intents: Intents.ALL,
    },
});
```
